# Generated by Django 5.2 on 2025-05-13 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Symptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("SEVERE", "Severe"),
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                        ],
                        default="MILD",
                        max_length=15,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("neck", "Neck"),
                            ("chest", "Chest"),
                            ("abdomen", "Abdomen"),
                            ("back", "Back"),
                            ("left_arm", "Left_Arm"),
                            ("left_leg", "Left_Leg"),
                            ("right_arm", "Right_Arm"),
                            ("right_leg", "Right_Leg"),
                            ("pelvis", "Pelvis"),
                            ("whole_body", "Whole Body"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("triggers", models.CharField(blank=True)),
                ("relief", models.CharField(blank=True)),
                ("notes", models.CharField(blank=True)),
            ],
        ),
    ]
